if: branch !~ /^docs/

language: java
dist: trusty
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

env:
  - OS=Windows BROWSER=Chrome
  - OS=Windows BROWSER=Firefox
  - OS=Windows BROWSER=Edge
  - OS=Windows BROWSER=IE
  - OS="OS X" BROWSER=Safari

matrix:
  include:
    - name: "Tests - local FF"
      addons:
        firefox: "68.0"
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
      script: mvn clean install -Dwebdriver.type=firefox -Dwebdriver.firefox.bin="$(which firefox)"
    - name: "SonarCloud"
      addons:
        sonarcloud:
          organization: "bobcat-github"
          token:
            secure: $SONAR_TOKEN
      script: sonar-scanner

script:
  - mvn clean install -Dwebdriver.type=remote -Dwebdriver.url="https://$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_TOKEN@hub-cloud.browserstack.com/wd/hub" -Dwebdriver.cap.browser="$BROWSER" -Dwebdriver.cap.os="$OS"
